spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOSTNAME:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
